In [1]:
#1. Write a NumPy program to multiply two given arrays of same size element-by-element

In [2]:
import numpy as np

In [3]:
n1=np.array([[2,2],[2,2]],np.int16)

In [4]:
n2=np.array([[2,2],[2,2]],np.int16)

In [5]:
result=np.multiply(n1,n2)

In [6]:
result



array([[4, 4],
       [4, 4]], dtype=int16)

In [7]:
#Write a NumPy program to find the missing data in a given array.

In [8]:
a1=np.array([[1,2,3,np.nan,4],[1,np.nan,2,np.nan,np.nan]])

In [9]:
nanResult=np.isnan(a1)

In [10]:
nanResult

array([[False, False, False,  True, False],
       [False,  True, False,  True,  True]])

In [11]:
#3. Write a NumPy program to test whether each element of a 1-D array is also present in a second array


In [12]:
a2=np.array([1,2,3,4])

In [13]:
a3=np.array([2,4,5,6,7])

In [14]:
doesExist=np.isin(a2,a3)

In [15]:
doesExist

array([False,  True, False,  True])

In [16]:
#4. Write a NumPy program to save a NumPy array to a text file.

In [17]:
arr=np.array([[1,2,3,4],[2,3,4,7]])

In [18]:
np.savetxt("numpyQuestion4.txt",arr,fmt='%d',delimiter=',')

In [19]:
file=open("numpyQuestion4.txt","r")

In [20]:
data=file.read()

In [21]:
data


'1,2,3,4\n2,3,4,7\n'

In [22]:
#Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between 2.5 and 6.5 inclusive

In [23]:
arr2=np.linspace(2.5,6.5,30)

In [24]:
arr2

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

In [25]:
import pandas as pd

In [26]:
#1. Write a Pandas program to convert Series of lists to one Series.

In [27]:
series=pd.Series([[1,3,4],[2,3,6]])

In [28]:
series

0    [1, 3, 4]
1    [2, 3, 6]
dtype: object

In [29]:
series=series.explode()

In [30]:
series

0    1
0    3
0    4
1    2
1    3
1    6
dtype: object

In [31]:
series1=pd.Series([1,2,3],[4,5,6])

In [32]:
series

0    1
0    3
0    4
1    2
1    3
1    6
dtype: object

In [33]:
series1

4    1
5    2
6    3
dtype: int64

In [34]:
series.shape

(6,)

In [35]:
series1.shape


(3,)

In [36]:
#2. Write a Pandas program to create a subset of a given series based on value and condition.


In [37]:
series2 = pd.Series([1,2,3,4,5,3,1,3,3,5,6,7,8,9,1,1,1,2,2,2])

In [38]:
resultSeries2=series2[series2>3]


In [39]:
resultSeries2

3     4
4     5
9     5
10    6
11    7
12    8
13    9
dtype: int64

In [40]:
#3. Write a Pandas program to display most frequent value in a given series and replace everything else as others in the series.


In [41]:
series3=pd.Series([1,2,3,4,4,4,4,4,5,2,2,1,1,23,4,4,5,5,3,3])

In [42]:
resultSeries3=series3.mode()

In [43]:
resultSeries3

0    4
dtype: int64

In [44]:
my_series = pd.Series([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
most_frequent_value = my_series.mode().iloc[0]
my_series = my_series.apply(lambda x: most_frequent_value if x == most_frequent_value else 'Other')

print(my_series)

0    Other
1    Other
2    Other
3    Other
4    Other
5    Other
6        4
7        4
8        4
9        4
dtype: object


In [45]:
#4. Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series.
my_series = pd.Series([1, 5, 10, 15, 20, 25, 30, 35, 40])

positions_of_multiples_of_5 = my_series.index[my_series % 5 == 0]

print("Original Series:")
print(my_series)

print("\nPositions of numbers that are multiples of 5:")
print(positions_of_multiples_of_5)


Original Series:
0     1
1     5
2    10
3    15
4    20
5    25
6    30
7    35
8    40
dtype: int64

Positions of numbers that are multiples of 5:
Int64Index([1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')


In [46]:
#5. Write a Pandas program to calculate the number of characters in each word in a given series.


In [47]:
import pandas as pd

my_series = pd.Series(['shubham', 'subash', 'srijan', 'shreyan'])
word_lengths = my_series.str.len()





print(word_lengths)

0    7
1    6
2    6
3    7
dtype: int64


In [48]:
#6. Write a Pandas program to convert year-month string to dates adding a specified day of the month.


In [51]:
year_month_strings = pd.Series(['2022-01', '2022-02', '2022-03', '2022-04'])
specified_day = 6

dates_with_specified_day = pd.to_datetime(year_month_strings + '-' + str(specified_day), format='%Y-%m-%d')

result_df = pd.DataFrame({
    'Year-Month String': year_month_strings,
    'Converted Date': dates_with_specified_day
})

print(result_df)

  Year-Month String Converted Date
0           2022-01     2022-01-06
1           2022-02     2022-02-06
2           2022-03     2022-03-06
3           2022-04     2022-04-06


In [52]:
#7. Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.


In [53]:
data = {
    'Name': ['shubham', 'rishab', 'rahul', 'srijan'],
    'Age': [20, 19, 20, 19],
    'City': ['India', 'berlin', 'Birgunj', 'Nepalgunj']
}
index_labels = ['Person1', 'Person2', 'Person3', 'Person4']
df = pd.DataFrame(data, index=index_labels)

print(df)

            Name  Age       City
Person1  shubham   20      India
Person2   rishab   19     berlin
Person3    rahul   20    Birgunj
Person4   srijan   19  Nepalgunj


In [54]:
#8. Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.


In [55]:
data = {
    'Student': ['shubham', 'srijan', 'utkarsh', 'Baahu'],
    'Attempts': [1, 4, 3, 2]
}
df = pd.DataFrame(data)
selected_rows = df[df['Attempts'] > 2]

print("Original DataFrame:")
print(df)

print("\nSelected rows where the number of attempts is greater than 2:")
print(selected_rows)

Original DataFrame:
   Student  Attempts
0  shubham         1
1   srijan         4
2  utkarsh         3
3    Baahu         2

Selected rows where the number of attempts is greater than 2:
   Student  Attempts
1   srijan         4
2  utkarsh         3


In [56]:
#9. Write a Pandas program to append a new row &#39;k&#39; to data frame with given values for each column. Now delete the new row and return the original DataFrame.


In [57]:
data = {'Name': ['Armani','Ramani','Krishan','Anu']}
df = pd.DataFrame(data)

new_row_values = {'Name': 'Likhita'}
df = pd.concat([df, pd.DataFrame([new_row_values])], ignore_index=True)

print("DataFrame with New Row:")
print(df)

df = df.drop(df[df['Name'] == 'Likhita'].index)

print("\nOriginal DataFrame after Deleting 'Likhita':")
print(df)

DataFrame with New Row:
      Name
0   Armani
1   Ramani
2  Krishan
3      Anu
4  Likhita

Original DataFrame after Deleting 'Likhita':
      Name
0   Armani
1   Ramani
2  Krishan
3      Anu


In [58]:
#10. Write a Pandas program to sort the DataFrame first by &#39;name&#39; in descending order,then by &#39;score&#39; in ascending order.


In [60]:
data = {
    'Name': ['Anu','Nimiss','lia','Nancy'],
    'Score': [100, 69, 80, 35]
}
df = pd.DataFrame(data)
df_sorted = df.sort_values(by=['Name', 'Score'], ascending=[False, True])

print("DataFrame sorted by 'Name' in descending order, then by 'Score' in ascending order:")
print(df_sorted)

DataFrame sorted by 'Name' in descending order, then by 'Score' in ascending order:
     Name  Score
2     lia     80
1  Nimiss     69
3   Nancy     35
0     Anu    100


In [61]:
#11. Write a Pandas program to replace the &#39;qualify&#39; column contains the values &#39;yes&#39; and &#39;no&#39; with True and False.


In [63]:
data = {
    'Name': ['bikesh','keshav','broran','Nikhila'],
    'Qualify': ['yes', 'no', 'yes', 'no']
}
df = pd.DataFrame(data)
df['Qualify'] = df['Qualify'].replace({'yes': True, 'no': False})

print("DataFrame after replacing 'qualify' values:")
print(df)

DataFrame after replacing 'qualify' values:
      Name  Qualify
0   bikesh     True
1   keshav    False
2   broran     True
3  Nikhila    False


In [64]:
#12. Write a Pandas program to remove infinite values from a given DataFrame.

In [65]:
data = {
    'Name': ['shreyans','puja','sunita','sangeeta'],
    'Score': [90, np.inf, 75, -np.inf]
}
df = pd.DataFrame(data)
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df_cleaned = df.dropna()

print("Original DataFrame:")
print(df)

print("\nDataFrame after removing infinite values:")
print(df_cleaned)

Original DataFrame:
       Name  Score
0  shreyans   90.0
1      puja    NaN
2    sunita   75.0
3  sangeeta    NaN

DataFrame after removing infinite values:
       Name  Score
0  shreyans   90.0
2    sunita   75.0
